// AUTO-GENERATED by scripts/generate-locations.cjs
export const locations = [
  {
    name: "Abim",
    count: 98,
  },
  {
    name: "Adjumani",
    count: 68,
  },
  {
    name: "Agago",
    count: 23,
  },
  {
    name: "Alebtong",
    count: 116,
  },
  {
    name: "Amolatar",
    count: 85,
  },
  {
    name: "Amudat",
    count: 109,
  },
  {
    name: "Amuria",
    count: 86,
  },
  {
    name: "Amuru",
    count: 99,
  },
  {
    name: "Apac",
    count: 1,
  },
  {
    name: "Arua",
    count: 2,
  },
  {
    name: "Budaka",
    count: 100,
  },
  {
    name: "Bududa",
    count: 106,
  },
  {
    name: "Bugiri",
    count: 69,
  },
  {
    name: "Bugweri",
    count: 36,
  },
  {
    name: "Buhweju",
    count: 20,
  },
  {
    name: "Buikwe",
    count: 110,
  },
  {
    name: "Bukedea",
    count: 107,
  },
  {
    name: "Bukomansimbi",
    count: 126,
  },
  {
    name: "Bukwo",
    count: 87,
  },
  {
    name: "Bulambuli",
    count: 117,
  },
  {
    name: "Buliisa",
    count: 101,
  },
  {
    name: "Bundibugyo",
    count: 3,
  },
  {
    name: "Bunyangabu",
    count: 29,
  },
  {
    name: "Bushenyi",
    count: 4,
  },
  {
    name: "Busia",
    count: 70,
  },
  {
    name: "Butaleja",
    count: 88,
  },
  {
    name: "Butambala",
    count: 127,
  },
  {
    name: "Butebo",
    count: 30,
  },
  {
    name: "Buvuma",
    count: 118,
  },
  {
    name: "Buyende",
    count: 111,
  },
  {
    name: "Dokolo",
    count: 102,
  },
  {
    name: "Gomba",
    count: 119,
  },
  {
    name: "Gulu",
    count: 5,
  },
  {
    name: "Hoima",
    count: 6,
  },
  {
    name: "Ibanda",
    count: 89,
  },
  {
    name: "Iganga",
    count: 7,
  },
  {
    name: "Isingiro",
    count: 90,
  },
  {
    name: "Jinja",
    count: 8,
  },
  {
    name: "Kaabong",
    count: 91,
  },
  {
    name: "Kabale",
    count: 9,
  },
  {
    name: "Kabarole",
    count: 10,
  },
  {
    name: "Kaberamaido",
    count: 82,
  },
  {
    name: "Kagadi",
    count: 25,
  },
  {
    name: "Kakumiro",
    count: 26,
  },
  {
    name: "Kalaki",
    count: 129,
  },
  {
    name: "Kalangala",
    count: 21,
  },
  {
    name: "Kaliro",
    count: 92,
  },
  {
    name: "Kalungu",
    count: 11,
  },
  {
    name: "Kampala",
    count: 32,
  },
  {
    name: "Kamuli",
    count: 42,
  },
  {
    name: "Kamwenge",
    count: 74,
  },
  {
    name: "Kanungu",
    count: 83,
  },
  {
    name: "Kapchorwa",
    count: 43,
  },
  {
    name: "Kapelebyong",
    count: 37,
  },
  {
    name: "Karenga",
    count: 130,
  },
  {
    name: "Kasanda",
    count: 38,
  },
  {
    name: "Kasese",
    count: 44,
  },
  {
    name: "Katakwi",
    count: 71,
  },
  {
    name: "Kayunga",
    count: 75,
  },
  {
    name: "Kazo",
    count: 132,
  },
  {
    name: "Kibaale",
    count: 45,
  },
  {
    name: "Kiboga",
    count: 46,
  },
  {
    name: "Kibuku",
    count: 13,
  },
  {
    name: "Kikuube",
    count: 39,
  },
  {
    name: "Kiruhura",
    count: 93,
  },
  {
    name: "Kiryandongo",
    count: 120,
  },
  {
    name: "Kisoro",
    count: 47,
  },
  {
    name: "Kitagwenda",
    count: 133,
  },
  {
    name: "Kitgum",
    count: 48,
  },
  {
    name: "Koboko",
    count: 94,
  },
  {
    name: "Kole",
    count: 14,
  },
  {
    name: "Kotido",
    count: 49,
  },
  {
    name: "Kumi",
    count: 50,
  },
  {
    name: "Kwania",
    count: 40,
  },
  {
    name: "Kween",
    count: 15,
  },
  {
    name: "Kyankwanzi",
    count: 121,
  },
  {
    name: "Kyegegwa",
    count: 112,
  },
  {
    name: "Kyenjojo",
    count: 76,
  },
  {
    name: "Kyotera",
    count: 31,
  },
  {
    name: "Lamwo",
    count: 113,
  },
  {
    name: "Lira",
    count: 51,
  },
  {
    name: "Luuka",
    count: 122,
  },
  {
    name: "Luweero",
    count: 52,
  },
  {
    name: "Lwengo",
    count: 16,
  },
  {
    name: "Lyantonde",
    count: 108,
  },
  {
    name: "Madi-okollo",
    count: 134,
  },
  {
    name: "Manafwa",
    count: 95,
  },
  {
    name: "Maracha",
    count: 105,
  },
  {
    name: "Masaka",
    count: 53,
  },
  {
    name: "Masindi",
    count: 54,
  },
  {
    name: "Mayuge",
    count: 77,
  },
  {
    name: "Mbale",
    count: 55,
  },
  {
    name: "Mbarara",
    count: 56,
  },
  {
    name: "Mitooma",
    count: 17,
  },
  {
    name: "Mityana",
    count: 96,
  },
  {
    name: "Moroto",
    count: 57,
  },
  {
    name: "Moyo",
    count: 135,
  },
  {
    name: "Mpigi",
    count: 58,
  },
  {
    name: "Mubende",
    count: 59,
  },
  {
    name: "Mukono",
    count: 60,
  },
  {
    name: "Nabilatuk",
    count: 41,
  },
  {
    name: "Nakapiripirit",
    count: 84,
  },
  {
    name: "Nakaseke",
    count: 97,
  },
  {
    name: "Nakasongola",
    count: 72,
  },
  {
    name: "Namayingo",
    count: 123,
  },
  {
    name: "Namisindwa",
    count: 33,
  },
  {
    name: "Namutumba",
    count: 103,
  },
  {
    name: "Napak",
    count: 18,
  },
  {
    name: "Nebbi",
    count: 61,
  },
  {
    name: "Ngora",
    count: 19,
  },
  {
    name: "Ntoroko",
    count: 124,
  },
  {
    name: "Ntungamo",
    count: 62,
  },
  {
    name: "Nwoya",
    count: 22,
  },
  {
    name: "Obongi",
    count: 136,
  },
  {
    name: "Omoro",
    count: 27,
  },
  {
    name: "Otuke",
    count: 114,
  },
  {
    name: "Oyam",
    count: 104,
  },
  {
    name: "Pader",
    count: 78,
  },
  {
    name: "Pakwach",
    count: 34,
  },
  {
    name: "Pallisa",
    count: 63,
  },
  {
    name: "Rakai",
    count: 64,
  },
  {
    name: "Rubanda",
    count: 28,
  },
  {
    name: "Rubirizi",
    count: 24,
  },
  {
    name: "Rukiga",
    count: 35,
  },
  {
    name: "Rukungiri",
    count: 65,
  },
  {
    name: "Rwampara",
    count: 137,
  },
  {
    name: "Serere",
    count: 125,
  },
  {
    name: "Sheema",
    count: 12,
  },
  {
    name: "Sironko",
    count: 79,
  },
  {
    name: "Soroti",
    count: 66,
  },
  {
    name: "Ssembabule",
    count: 73,
  },
  {
    name: "Tororo",
    count: 67,
  },
  {
    name: "Wakiso",
    count: 80,
  },
  {
    name: "Yumbe",
    count: 81,
  },
  {
    name: "Zombo",
    count: 115,
  },
] as const;
